server {
    # Nginx mendengarkan request HTTP di port 80 di dalam container
    listen 80;

    # Menentukan folder tempat file hasil build Vite disimpan. Di Dockerfile, folder dist disalin ke lokasi ini.
    root /usr/share/nginx/html; 
    
    # File default yang dikirim saat user membuka root path seperti /.
    index index.html;

    # Nginx mencoba mencari file sesuai path. Kalau tidak ada, fallback ke index.html.
    location / {
        try_files $uri $uri/ /index.html;
    }
}